export const COUNTRIES: string[] = [
    "Afghanistan",
    "Argentina",
    "Belarus",
    "Bouvet Island",
    "Cambodia",
    "Cocos (Keeling) Islands",
    "Cyprus",
    "Eritrea",
     "French Southern Territories",
    "Guadeloupe",
    "Honduras",
    "Isle of Man",
    "Kuwait",
    "Luxembourg",
    "Finland",
    "Martinique",
    "Montserrat",
    "Nicaragua",
    "Palau",
    "Puerto Rico",
    "Saint Lucia",
    "Seychelles",
    "Korea (Republic of)",
    "Syrian Arab Republic",
    "Tunisia",
    "United States",
    "Uruguay"
]